[platformio]
default_envs = bluepill_f103c8

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
monitor_speed = 115200
test_build_src = yes
build_flags = -Iconfig

[env:native]
platform = native
test_build_src = yes
build_flags =
    -Iconfig
build_src_filter =
    +<pointer_protocol.cpp>
